### ISSUE TITLE
func is_valid crashed when checking '*/0 * * * *' cron string

### ISSUE THREAD

**Issue by wfgydbu** [taichino/croniter#114]
Hi guys. 

Accidentally found an issue when using `is_valid` func with parameter '*/0 * * * *', the expect return is False, while somehow the program crashed.

I actually located where the problem is, it's in croniter.py Line 499. `m.group(4) or 1` failed to return `1` when `m.group(4) == '0'`, which then further caused variable `step` became 0, then it crashed. 

Could you please fix this?

**Comment by kiorky** [comment]
Uhm, i need to investigate but your cron line seems invalid for me, so at least its normal that it wont work.

*/0 mean each 0 minutes, division by zero !

**Comment by wfgydbu** [comment]
As a programmer, I totally understand this cron line is invalid, and stupid! But we cannot control that somebody attempts  to do this to let their jobs run continually. 

Thanks for working on this!

**Comment by kiorky** [comment]
Ok, no problemo, as i said i ll look how to make croniter not crash.
I wanted just to be clear on the invalidness of the expressions.
thx for reporting !

**Comment by kiorky** [comment]
https://pypi.org/project/croniter/0.3.27/ is out

**Comment by wfgydbu** [comment]
Fabulous! Thansk.

**Comment by kiorky** [comment]
Better later than never ^^ :).
