### ISSUE TITLE
Croniter fails at a given weekday range of "Mon-Sun"

### ISSUE THREAD

**Issue by Brat-Wurscht** [taichino/croniter#119]
It can handle "Sun-Sat", but not "Mon-Sun". According to the cron logic, both notations should be valid.

`0 - Sun`
`1 - Mon`
`2 - Tue`
`3 - Wed`
`4 - Thu`
`5 - Fri`
`6 - Sat`
`7 - Sun`

**Comment by kiorky** [comment]
Hello, What is the code falling behind that incomplete report ?

**Comment by kiorky** [comment]
https://pypi.org/project/croniter/0.3.27/ is out
