### ISSUE TITLE
croniter interprets length 6 cron entries as seconds

### ISSUE THREAD

**Issue by eswan18** [taichino/croniter#122]
Great package! Really handy.

However, I spent a lot of time debugging an issue because I assumed that a length 6 entry (* * * * * *) would be interpreted *minute-hour-date-month-day-year*. Instead, seems to be interpreted as *second-minute-hour-date-month-day*. The [wikipedia entry for cron](https://en.wikipedia.org/wiki/Cron) shows the former, thus my confusion:

![image](https://user-images.githubusercontent.com/3449508/53243719-c7f0d200-3676-11e9-8916-3fe1abe60920.png)

I think this is a big problem not only because of the confusion it might cause to people googling for the cron spec (like myself), but also because it causes very inconsistent behavior of `get_next()`.
See below.

If you specify a length 5 cron entry, get_next returns datetimes every minute:

![image](https://user-images.githubusercontent.com/3449508/53243892-464d7400-3677-11e9-886a-645a0526969e.png)

But if you specify a length 6 cron entry, suddenly it switches to every second.

![image](https://user-images.githubusercontent.com/3449508/53243919-5bc29e00-3677-11e9-8d87-db5a1492e146.png)

If you want to keep this behavior, it would be great for it to be documented better -- and perhaps for croniter to issue a warning when the user attempts a length 6 entry.

**Comment by kiorky** [comment]
I also agree, but we support also a bit second repeats, see https://github.com/taichino/croniter/commit/4f1a48483b1a77b3f14b64a91ccb5e879510863a.

We need to handle the '* '* * * *'...

I ll see to do that :)

**Comment by kiorky** [comment]
[0.3.32](https://pypi.org/project/croniter/) is out !
