### ISSUE TITLE
Improper processing of cron strings with specific formats

### ISSUE THREAD

**Issue by ylockerman** [taichino/croniter#142]
Hi,

I have been running some tests on croniter and noticed some bugs with specific classes of cron strings.

The first is strings where both the day of the month and day of the week are defined but the day of the month will never be reached. According to the normal cron semantics, the day of the week should be used to generate dates. For example, the string "48 14 31 jun sun" will never generate any dates. However, it should be valid on 14:48 on every Sunday in June. The root of this issue seems to be that the [code that tries to process the exception](https://github.com/taichino/croniter/blob/18b20ac72b156b4e262d733ff58807807731c942/src/croniter/croniter.py#L201) does not catch exceptions. Thus, if the day of the month has no valid dates, the code propagates the exception to the user instead of checking the day of the week.

The second is strings that contain an "l" in the day of the month along with a slash or dash. For example: "35 * 0-l/8 8 *". In these cases, [the code attempts to convert the "l" into an integer](https://github.com/taichino/croniter/blob/18b20ac72b156b4e262d733ff58807807731c942/src/croniter/croniter.py#L530) which fails. The [corresponding code in the other branch](https://github.com/taichino/croniter/blob/18b20ac72b156b4e262d733ff58807807731c942/src/croniter/croniter.py#L566) checks to see if the text is "l" before proceeding.

Thank you

**Comment by kiorky** [comment]
1. `48 14 31 jun sun` is an invalid cron, `48 14 31 jun sun` is grammatically valid but doesn't have any sense.
2. handled by 614d74e
