### ISSUE TITLE
Method to know if the cron expression is recurring or one time

### ISSUE THREAD

**Issue by connessionetech** [taichino/croniter#146]
Is there a way to know whether the cron expression is recurring or one time only?  can the get_next method be used for this somehow or is there an alternative way of getting this info?

**Comment by kiorky** [comment]
It depends on how you want, as searching for year can take CPU Cycle, but yes, you have get_next, and all_next in the latest (just now) released croniter version that can get you all times occurrences selectable by a crontab expression, the introduced param `max_years_between_matches` in the latest release can let you search occurences in timespan greater than the default 50 years.
