### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by trendelkampschroer** [taichino/croniter#150]
Hi, thanks a lot for creating croniter and making it available to the public.

Do you plan to release a first version `1.0` for which you guarantee a "stable" interface?

That could be helpful for people who use croniter as a dependency in their code.

**Comment by kiorky** [comment]
interface is stable for years, nothing has drastically changed at the point to change to a new major version.

**Comment by kiorky** [comment]
![image](https://user-images.githubusercontent.com/90111/96884325-aebeab00-1481-11eb-810c-8f413cff9152.png)

For now croniter does not added any invasive change that introduced api breakage.

We may change the minor in the next release as we will introduce some new code to handle better DST transition, but the major will not change, for 1.

**Comment by MisguidedEmails** [comment]
That's a bit unfortunate as the [semver guidelines](https://semver.org/#spec-item-4) also state that `0.x.y` versions indicate it has an unstable API. [They say](https://semver.org/#how-do-i-know-when-to-release-100) if it's stable or used in production it should ideally be released as `1.x.y`

I wonder if it's worth stating this in the readme so people know the API is stable even though it's `0.x`

**Comment by kiorky** [comment]
Please see changelog, croniter is 11 years old. 

It would have been known if it would not be stable.

**Comment by kiorky** [comment]
btw, i will just make another commit release for making you happy ;)

**Comment by kiorky** [comment]
1.0.1 released.

**Comment by MisguidedEmails** [comment]
Sorry wasn't trying to push for a 1.0 release, but I do appreciate it regardless, thanks! (only stumbled across this as I've been using it for a few years and was curious about 1.x)

**Comment by kiorky** [comment]
no problem, if you felt there was something todo, there was certainly something todo.

**Comment by trendelkampschroer** [comment]
Thanks for releasing `1.0.1`! This will further increase the usefulness for projects which rely on semver guidelines to reason about API stability (thanks to @MisguidedEmails for linking the relevant specifications).

**Comment by kiorky** [comment]
Sorry, but i can't let you say that @trendelkampschroer, it's truely abusive.

It's only for semver where a 0.X release implies it's on a development state.

croniter was for now NOT USING SEMVER but regular library versioning so you can't access that, SORRY.

a good exemple would be https://en.wikipedia.org/wiki/OpenSSL which turned 1.0 long time after initial stable release ;-)

**Comment by trendelkampschroer** [comment]
My apologies if my comment came along as abusive. 

My intent was purely to sincerly thank you for cutting a release.

In addition I wanted to express that it's more convenient for external dependencies to have major version > 0 IF developers/projects are used to reason about API stability in terms of semver. 

So thank you again for making croniter available and cutting this release and sorry that this wasn't clear from the wording of my comment.
