### ISSUE TITLE
match fails on last microsecond of minute

### ISSUE THREAD

**Issue by craigbarratt** [taichino/croniter#151]
Using `croniter-0.3.35`:
```python
from datetime import datetime as dt
from croniter import croniter

croniter.match("* * * * *", dt(2019, 1, 14, 11, 0, 59, 999999))
```
returns `False`.  Values other than 59.999999 correctly return `True`.

**Comment by craigbarratt** [comment]
Is there any update on this issue?  Is this the right place to submit bug reports?

**Comment by kiorky** [comment]
It's the right place, sorry your issue felt into github limbs !

Well, granularity of cron is minute paced.

I ll see if i can do something for this specific case.

**Comment by kiorky** [comment]
1.0.2 has the fix.
