### ISSUE TITLE
croniter accepts syntactically incorrect cron expressions

### ISSUE THREAD

**Issue by cuu508** [taichino/croniter#157]
I found a few cases where croniter accepts a malformed cron expression. 

croniter accepts `1-1_0 * * * *` and interprets it as `1-10 * * * *`

When parsing *range with a step*, croniter uses int(), which accepts underscores for grouping digits.

---

croniter accepts `0-10/ * * * *` and interprets it as `0-10/1 * * * *`

The `step_search_re` allows for an empty step, and substitutes the empty step with "1" 

---

A slightly different problem: inconsist handling of lowercase and uppercase "L". 

croniter accepts `* * 10-l * *` but rejects `* * 10-L * *`. 

Perhaps it should convert the expression to lowercase as an early step during the parsing.

**Comment by cuu508** [comment]
PS. I'm happy to try my hand at writing a PR for fixing each of the above.

**Comment by kiorky** [comment]
If you can make the PR, yes a big thanks as i can't do it quickly for now, can you make them on https://github.com/kiorky/croniter ?

**Comment by kiorky** [comment]
https://pypi.org/project/croniter/1.0.7/ is out, do we have something more to close this bug @cuu508 ?
And, again, thanks a lot !

**Comment by cuu508** [comment]
I'd like to, but haven't yet made a PR for the `* * 10-l * *` and `* * 10-L * *` inconsistency. 

(I wanted to do each fix in a separate PR, but didn't want to do too many at the time, to not run into merge conflicts.)

**Comment by kiorky** [comment]
Please proceed next then, :=)

**Comment by kiorky** [comment]
Everything done here, afterall ?

**Comment by cuu508** [comment]
Yes – thank you for reviewing and accepting these PRs!
