### ISSUE TITLE
Feature request: Jenkins-style hashed format, random format

### ISSUE THREAD

**Issue by rfinnie** [taichino/croniter#162]
Hi, I maintain an extension to croniter called [croniter_hash](https://github.com/rfinnie/rf-pymods#croniter_hash), which adds Jenkins-style "H" hashing:

```python
epoch = datetime(2020, 1, 1, 0, 0)
# Each hashed definition is consistent to its specified hash_id
croniter_hash("H H * * *", epoch, hash_id="hello").get_next(datetime)
"""datetime.datetime(2020, 1, 1, 11, 10)"""
croniter_hash("H H * * *", epoch, hash_id="hello").get_next(datetime)
"""datetime.datetime(2020, 1, 1, 11, 10)"""
croniter_hash("H H * * *", epoch, hash_id="bonjour").get_next(datetime)
"""datetime.datetime(2020, 1, 1, 20, 52)"""
```

Would you be receptive to upstreaming this? I can prepare a PR, or if you'd like to implement it yourself that's fine, I just wanted to gauge interest before I start.

(croniter_hash also implements actual random "R" definitions, but I'm ambivalent about that, as "H" definitions have proven to be more useful in the wild.)

**Comment by kiorky** [comment]
As the extension seems not invasive, of course, it's welcome, you can go ahead and make a PR to merge it into croniter baseclass although the codebase should remain py2 compatible.

Do not forget to add you to contributors, add something to doc/changes and an usage example in the readme :).

https://github.com/rfinnie/rf-pymods/blob/main/rf_pymods/croniter_hash.py#L39 at least seems problematic.

**Comment by kiorky** [comment]
Please make the fork/PR against https://github.com/kiorky/croniter (see this repo readme ;))

**Comment by kiorky** [comment]
Also, for all regexes, please use compiled form, for performance, and try to use raw match (no regexes) (like split to int cast).

Regexes overuse can do a great performance hit.

**Comment by rfinnie** [comment]
> As the extension seems not invasive, of course, it's welcome, you can go ahead and make a PR to merge it into croniter baseclass although the codebase should remain py2 compatible.
> 
> https://github.com/rfinnie/rf-pymods/blob/main/rf_pymods/croniter_hash.py#L39 at least seems problematic.

You mean I have to re-remember py2 oddities? :)  Actually, I think that code will work on py2 and pass to binascii.crc32 correctly, but I'll make sure it passes the full tox suite.

> Do not forget to add you to contributors, add something to doc/changes and an usage example in the readme :).

Ack.

> Please make the fork/PR against https://github.com/kiorky/croniter (see this repo readme ;))

Ack, though I'm a bit confused about the fork split. kiorky/croniter is mentioned in the README, but taichino/croniter seems to be kept up to date with the fork, and has the issue tracker. Maybe clarify a bit in the README?

> Also, for all regexes, please use compiled form, for performance, and try to use raw match (no regexes) (like split to int cast).
>
> Regexes overuse can do a great performance hit.

Sigh, didn't notice I was doing that. I love Python, but hate how non-compiled regexes incur a real performance hit.  I'll get that compiled, and I should be able to collapse all item checks into one regex by using named matches.

Thanks!

**Comment by kiorky** [comment]
> Ack, though I'm a bit confused about the fork split. kiorky/croniter is mentioned in the README, but taichino/croniter seems to be kept up to date with the fork, and has the issue tracker. Maybe clarify a bit in the README?

@taichino was the first author, but abandoned it a long time, i maintain now croniter for more than a decade.

I will eventually see with him if we can suceed to make some github foo to sweep off the repos fork direction
