### ISSUE TITLE
Source code license?

### ISSUE THREAD

**Issue by randlet** [taichino/croniter#167]
This is a nice package and looks like it's widely used (including as an option in Django Q which I really like!). However, there is no license associated with the code which I believe means that anyone using this code is in violation of the authors rights (see https://choosealicense.com/no-permission/).  

From [GitHub's licensing docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license):

> We created choosealicense.com, to help you understand how to license your code. A software license tells others what they can and can't do with your source code, so it's important to make an informed decision.
> 
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. 
> 

If this is the authors intent, then carry on!  However, if you want to enable people to use and/or modify the code then it would be appreciated if you could add an appropriate license to the project.

**Comment by randlet** [comment]
After posting that I see that the MIT license is actually specified in [setup.py](https://github.com/taichino/croniter/blob/3ad5a947bc692ca504d0ce16194e0e1b8668fac9/setup.py#L38).  I will submit a PR to add the MIT license as a LICENSE file then.

**Comment by kiorky** [comment]
https://github.com/taichino/croniter/blob/master/docs/LICENSE
