### ISSUE TITLE
feature request, idea

### ISSUE THREAD

**Issue by pfpulux** [taichino/croniter#169]
Is there a plan to support thinks like: `every 3 weeks on wednesday` or `every odd week on monday`?

What you think about this?

**Comment by kiorky** [comment]
If you want to make a PR, you can use the plugin system we added a while in https://github.com/taichino/croniter/commit/b9cee97e2a4c3796437233f435d13cdb2e5e0a52 and i will be pleased to review it and merge it, but no, i have no plan to implement this myself.
