### ISSUE TITLE
TypeError: The start and stop must be same type.

### ISSUE THREAD

**Issue by olivierdalang** [taichino/croniter#170]
Hi !

In my tests, I get a TypeError exception (see detail below), due to this check https://github.com/taichino/croniter/blob/fc99d83a2ac6ef5795d5b39f732c55f80ecdfbe5/src/croniter/croniter.py#L798-L800

This is because I use freezegun, a library to freeze dates in tests.

IMO, this goes against the duck typing nature of python, and the check should be removed (if a check is needed, we should check if the needed attributes exist).

Let me know what you think.

Thanks for the otherwise awesome package !

Trace :
```
Traceback (most recent call last):
[...]
  File "...\site-packages\croniter\croniter.py", line 800, in croniter_range
    format(type(start), type(stop)))
TypeError: The start and stop must be same type.  <class 'datetime.datetime'> != <class 'freezegun.api.FakeDatetime'>
```

**Comment by kiorky** [comment]
i think i fixed your bug, see latest master.

**Comment by olivierdalang** [comment]
Thanks !
