### ISSUE TITLE
Document nonstandard cron expressions (L, #, W)

### ISSUE THREAD

**Issue by Safrone** [taichino/croniter#173]
Love the library but only realized nonstandard expressions were supported after doing a lot of digging and looking through the tests.

I think it's worth it to have a section for these like there is for H and R

**Comment by kiorky** [comment]
What's supported is i think already documented.

Did you saw a specific undocumented thing ?

**Comment by Safrone** [comment]
Ah I see it now. I though W was supported but unfortunately it does not appear to be (yet?)
