### ISSUE TITLE
Can croniter cron be set to a different TZ than the system?

### ISSUE THREAD

**Issue by merc1031** [taichino/croniter#175]
I beleive if the system TZ is set , ex TZ=America/Los_Angeles
normal cron can be specificied like this `0 0 0 * * TZ="Etc/UTC" /do/command > /dev/null 2>&1`
To treat the specific cron as if its in UTC time.

Is this something possible in the cron expression format of croniter?

**Comment by kiorky** [comment]
you may have a look to pytz and use a non-naive datetime.
