### ISSUE TITLE
Unexpected result for "0 0 8-9 * 0#2"

### ISSUE THREAD

**Issue by cuu508** [taichino/croniter#177]
I'm working on an experimental cron expression evaluator, and am testing it against croniter. I came across something that might be a bug. The expression:

```
0 0 8-9 * 0#2
```

I read it as *on midnight of every day that is either*:

* 8th of the month, 
* 9th of the month,
* the second Sunday of the month

Here's a snippet that generates the first 20 matching datetimes, starting from 2021-01-01:

```python
from datetime import datetime
from croniter import croniter

it = croniter("0 0 8-9 * 0#2", datetime(2021, 1, 1))

for i in range(0, 20):
    print(it.get_next(datetime).isoformat())

```

And here are the results:

```
2021-01-10T00:00:00
2021-02-14T00:00:00
2021-03-14T00:00:00
2021-04-11T00:00:00
2021-05-09T00:00:00
2021-06-13T00:00:00
2021-07-11T00:00:00
2021-08-08T00:00:00
2021-09-12T00:00:00
2021-10-10T00:00:00
2021-11-14T00:00:00
2021-12-12T00:00:00
2022-01-09T00:00:00
2022-02-13T00:00:00
2022-03-13T00:00:00
2022-04-10T00:00:00
2022-05-08T00:00:00
2022-06-12T00:00:00
2022-07-10T00:00:00
2022-08-14T00:00:00
```

Most 8ths and 9ths are missing from the output. I suspect this has something to do with the special handling of `#2` in the expression. If I test with "0 0 8-9 * 0", I get the result I expected:

```
2021-01-03T00:00:00
2021-01-08T00:00:00
2021-01-09T00:00:00
2021-01-10T00:00:00
2021-01-17T00:00:00
2021-01-24T00:00:00
2021-01-31T00:00:00
2021-02-07T00:00:00
2021-02-08T00:00:00
2021-02-09T00:00:00
2021-02-14T00:00:00
2021-02-21T00:00:00
2021-02-28T00:00:00
2021-03-07T00:00:00
2021-03-08T00:00:00
2021-03-09T00:00:00
2021-03-14T00:00:00
2021-03-21T00:00:00
2021-03-28T00:00:00
2021-04-04T00:00:00
```

**Comment by cuu508** [comment]
I'm not sure about this report any more – it seems cron itself is doing something weird here.

I ran an experiment:
* debian buster
* clock set to 2021-03-27 00:00
* one crontab entry: 

```
0 0 8-14 * 0#2 logger -t experiment `date -Iseconds`
```

I ran this in QEMU with an accelerated clock (using the "-icount" parameter) so I the experiment doesn't take a month of real time. It produced this output:

```
Mar 28 00:00:01 debian experiment[4795]: 2021-03-28T00:00:01+02:00
Apr 04 00:00:01 debian experiment[9110]: 2021-04-04T00:00:01+03:00
Apr 08 00:00:01 debian experiment[11618]: 2021-04-08T00:00:01+03:00
Apr 09 00:00:02 debian experiment[12244]: 2021-04-09T00:00:02+03:00
Apr 10 00:00:02 debian experiment[12916]: 2021-04-10T00:00:01+03:00
Apr 11 00:00:01 debian experiment[13539]: 2021-04-11T00:00:01+03:00
Apr 12 00:00:01 debian experiment[14134]: 2021-04-12T00:00:01+03:00
Apr 13 00:00:01 debian experiment[14760]: 2021-04-13T00:00:01+03:00
Apr 14 00:00:02 debian experiment[15431]: 2021-04-14T00:00:02+03:00
Apr 18 00:00:02 debian experiment[17873]: 2021-04-18T00:00:02+03:00
Apr 25 00:00:02 debian experiment[22253]: 2021-04-25T00:00:02+03:00
May 02 00:00:01 debian experiment[26678]: 2021-05-02T00:00:01+03:00
May 08 00:00:02 debian experiment[30424]: 2021-05-08T00:00:02+03:00
May 09 00:00:02 debian experiment[31048]: 2021-05-09T00:00:02+03:00
May 10 00:00:02 debian experiment[31682]: 2021-05-10T00:00:02+03:00
May 11 00:00:01 debian experiment[32264]: 2021-05-11T00:00:01+03:00
May 12 00:00:01 debian experiment[428]: 2021-05-12T00:00:01+03:00
May 13 00:00:01 debian experiment[1110]: 2021-05-13T00:00:01+03:00
May 14 00:00:02 debian experiment[1733]: 2021-05-14T00:00:02+03:00
[...]
```

From the output it looks like cron ignored the `#2` bit: it ran on every Sunday, not just on the second Sunday. I'm not sure if that's a bug in Debian's cron, a feature, or my test setup is broken.

**Comment by cuu508** [comment]
Ah, OK, looks like Debian's cron simply does not support the nth-weekday syntax.

* there is no mention of it in `man 5 crontab`
* looking at sources, `entry.c`, it does not look like it handles "#" in any special way when parsing crontab entries

What's interesting though is that cron accepts this syntax with no errors. In fact, I can put anything after the # character and cron does not complain, it just ignores it:

```
$ crontab -l
* * * * 3#this-is-silly logger hello world
```

Anyway, the original report is still relevant as croniter *does* support the nth-weekday syntax.

**Comment by kiorky** [comment]
croniter mostly stick with basic unix cron support and extra features are only community maintained.

I wont fix those bugs.

You can always (you will be welcome !) make a PR with additional support for those range topics with proper tests, and i wont see anything that would prevent me from merging them.

**Comment by cuu508** [comment]
I understand, this is a fairly obscure bug, and concerns a non-standard feature. 
I'm afraid I won't have time to fix this one either – I just came across it and thought the least I could do was to report it.
