### ISSUE TITLE
croniter('* * 0 * *') works

### ISSUE THREAD

**Issue by manishtomar** [taichino/croniter#23]
`croniter('* * 0 * *')` gives object that considers day of the month to be 1. I believe it should fail allowing entry between 1 to 31 only.

**Comment by manishtomar** [comment]
Has this been fixed? Or do you consider it not a bug?

**Comment by Sergei-Morozov** [comment]
even more
```
import croniter
value = "* * 0 0 *"
croniter.croniter.is_valid(value)
```

`day month` range is 1 - 31
`month` range is 1 - 12
