### ISSUE TITLE
croniter('* * * * 7') should fail

### ISSUE THREAD

**Issue by manishtomar** [taichino/croniter#24]
`croniter('* * * * 7')` should fail as day of the week is from 0-6 based on http://en.wikipedia.org/wiki/Cron#Format

**Comment by ipartola** [comment]
I don't believe so. Earlier in the same article:

"day of week (0 - 6) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)"

**Comment by manishtomar** [comment]
Oh sorry, didn't notice that diagram describing the week. Thanks for the info :). I am closing this.
