### ISSUE TITLE
Does not produce the correct output when the expression is something like (1-10/2 * * * *)

### ISSUE THREAD

**Issue by ShamiliVK** [taichino/croniter#29]
In the croniter.py file, line 89 should be changed from:
for j in xrange(int(low), int(high)+1):
         if j % int(step) == 0:
         e_list.append(j)
To:
for j in xrange(int(low), int(high)+1, int(step)):
         #if j % int(step) == 0:
         e_list.append(j)

Because, % returns intervals that are divisible by denominator between the start and end value whereas it should actually return start value plus the interval and next value should be result plus the interval and goes on.

After the change, the result will be like : [[1, 3, 5, 7, 9], ['_'], ['_'], ['_'], ['_']]

**Comment by josegonzalez** [comment]
This is covered by https://github.com/taichino/croniter/commit/ff142916ab691b1caf5e2a569b199c69ca49a405.
