### ISSUE TITLE
Python 2.6 support is broken

### ISSUE THREAD

**Issue by joostdevries** [taichino/croniter#44]
In [croniter.py](https://github.com/taichino/croniter/blob/080436e49376add75f4edd3d05805edea4e9637b/src/croniter/croniter.py#L158) the function [`timedelta.total_seconds`](https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds) is used. This function was added in 2.7 so support for 2.6 is broken by using this.

@petervtzand, I believe you mentioned that there's a simple fallback (`(td.microseconds + (td.seconds + td.days * 24 * 3600) * 10**6) / 10**6`)?

**Comment by petervtzand** [comment]
Yes
https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds

**Comment by harlowja** [comment]
Create a pull request?

**Comment by petervtzand** [comment]
Yes I will! If I find some time, maybe this week.

**Comment by kiorky** [comment]
dont forget to ping me on irc when you ll have a chance to push something, i ll be a lot afk in july (not for vacancy :(), but no worry, i ll get it in as fast as i can :)

**Comment by petervtzand** [comment]
Created a PR: https://github.com/taichino/croniter/pull/45
