### ISSUE TITLE
Error to get next time

### ISSUE THREAD

**Issue by gesanchez** [taichino/croniter#47]
Hello,

I am trying to get next date, but this method return it a previous date to the current date

Example

```
cron = croniter.croniter("%s %s %s %s %s" % (x.recurrence.minute, x.recurrence.hour, x.recurrence.day, x.recurrence.month, x.recurrence.weekday), x.recurrence.datestart)
cron.get_next()  -> This method return a previous date to the current date

datestart : 2015-09-18 15:40:00
get_next: 2015-09-18 15:41:00
```

**Comment by josegonzalez** [comment]
@gesanchez do you have the actual recurrence you're trying to test? The above doesn't give the information necessary to debug (and it looks like get_next is in the future, so I don't necessarily see a bug).

**Comment by kiorky** [comment]
invalid, no answer for 3 year :)
