### ISSUE TITLE
Incorrect `job.get_next()` time after DST (shift backwards)

### ISSUE THREAD

**Issue by petervtzand** [taichino/croniter#48]
I created a crontab that should run each monday at 8am, which works perfectly except for the first monday after the DST change in october (the clock is shifted an hour backwards). There is an extra schedule scheduled at 7am (as well as 8am), which you can see in the output.

This is my code

```
import croniter
import datetime
import pytz

#current time
current_time = datetime.datetime.now(tz=pytz.timezone('Europe/Amsterdam'))
crontab_string = "0 8 * * 1"  # every day monday at 0800

# create a job
job = croniter.croniter(crontab_string, current_time)

# print 
for i in range(0,200):
   print job.get_next(datetime.datetime)
```

This is my output

```
....
2017-10-16 08:00:00.685732+02:00
2017-10-23 08:00:00.685732+02:00
2017-10-30 07:00:00.685732+01:00
2017-10-30 08:00:00.685732+01:00
2017-11-06 08:00:00.685732+01:00
2017-11-13 08:00:00.685732+01:00
...
2018-10-15 08:00:00.685732+02:00
2018-10-22 08:00:00.685732+02:00
2018-10-29 07:00:00.685732+01:00
2018-10-29 08:00:00.685732+01:00
2018-11-05 08:00:00.685732+01:00
...
2019-10-07 08:00:00.685732+02:00
2019-10-14 08:00:00.685732+02:00
2019-10-21 08:00:00.685732+02:00
2019-10-28 07:00:00.685732+01:00
2019-10-28 08:00:00.685732+01:00
2019-11-04 08:00:00.685732+01:00
2019-11-11 08:00:00.685732+01:00
```

This bug doesn't appear when removing the timezone from the current time

**Comment by josegonzalez** [comment]
Personally I'd say the server time should always be in UTC so as to avoid these sorts of issues as much as possible.

**Comment by petervtzand** [comment]
@josegonzalez Yeah, all the times in my database are saved as UTC. But with crontab, I'd say it's very reasonable to deal with timezones and DST, because if one of my clients wants something scheduled every monday at 8, I'm not going to say to him: "yeah, from october till november it's scheduled at 8, otherwise at 7 because of DST.

**Comment by kiorky** [comment]
its your job to make naive or tz'd datetimes before/after croniter use.

**Comment by petervtzand** [comment]
@kiorky I did as you can see in the example..

**Comment by shaneharter** [comment]
I've also run into this bug in production last week during UK dst change.

**Comment by shaneharter** [comment]
@kiorky I've worked around this for now. I was wondering if you could provide a code sample that illustrates the proper way to handle this if it is indeed an implementation issue.
