### ISSUE TITLE
Run a job Every 5sec

### ISSUE THREAD

**Issue by Benoss** [taichino/croniter#53]
I am trying to run a job every 5 sec by adding a 6th *. Not sure if it is supposed to work

```
from croniter import croniter
from datetime import datetime
base = datetime(2010, 1, 25, 4, 46)
iter = croniter('*/5 * * * * *', base)  # every 5 sec
print iter.get_next(datetime)   # Should return 2010-01-25 04:46:05 but returns 2010-01-25 04:50:00
print iter.get_next(datetime)   # Should return  2010-01-25 04:46:10 but returns 2010-01-25 04:50:01
print iter.get_next(datetime)   # Should return  2010-01-25 04:46:15 but returns 2010-01-25 04:50:02
```

Am I missing something here?

**Comment by josegonzalez** [comment]
Seconds aren't part of the cron spec, so you won't be able to use this package for that.

**Comment by kiorky** [comment]
Yes for sure, thx in advance

**Comment by kiorky** [comment]
Ok, no stuff in 2 years, closing as wont fix :)

**Comment by liho00** [comment]
@kiorky @josegonzalez  Would you explain to me why dont we using */x * * * * * this format as every x second ?
but we using * * * * * */x as every x second?

https://crontab.cronhub.io/
<img width="871" alt="image" src="https://user-images.githubusercontent.com/77238199/202099195-298b2d7f-0263-45db-aa96-065b5a8c8101.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/77238199/202098992-387674b1-345a-4b45-97f3-636825add3b8.png">

**Comment by kiorky** [comment]
I dont support this code that was community contributed, that's why seconds repeats have only a partial support in croniter.

Croniter officially ony supports UNIX based cron (5 fields).

Feel free to submit a PR to fix seconds repeat, i ll be glad to merge it.
