### ISSUE TITLE
Development Issue: `python bootstrap.py -d` doesn't work

### ISSUE THREAD

**Issue by praveev** [taichino/croniter#58]
Two Issues:
1. `bootstrap.py: error: no such option: -d`
2. `-bash: bin/test: No such file or directory`

I was following the wiki to develop but encountered issues with running bootstrap as per instructions.

```
python bootstrap.py -d
Usage: [DESIRED PYTHON FOR BUILDOUT] bootstrap.py [options]

Bootstraps a buildout-based project.

Simply run this script in a directory containing a buildout.cfg, using the
Python that you want bin/buildout to use.

Note that by using --find-links to point to local resources, you can keep 
this script from going over the network.

bootstrap.py: error: no such option: -d
```

So I ignored the option and ran `python bootstrap`, which completed fine. 
Then followed this by running `bin/buildout -vvvvvvN`, which completed just fine.
But I don't see bin/test script in the repo. `-bash: bin/test: No such file or directory`

@kiorky

**Comment by josegonzalez** [comment]
The upgrade to `buildout2` dropped the `-d` flag, but this otherwise works under the following OSX environment:

```
[croniter] jose@mactaku:~/Apps/seatgeek/oss/croniter git:master $ python -V
Python 2.7.10
[croniter] jose@mactaku:~/Apps/seatgeek/oss/croniter git:master $ pip -V
pip 8.1.2 from /Users/jose/.virtualenvs/croniter/lib/python2.7/site-packages (python 2.7)
```

**Comment by kiorky** [comment]
and i just dropped buildout to a more modern approach (pip + tox)

**Comment by kiorky** [comment]
https://github.com/taichino/croniter#develop-this-package !??
