### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by josegonzalez** [taichino/croniter#62]
It doesn't look like travis is enabled, so builds aren't actually running for pull requests.

**Comment by kiorky** [comment]
it is but on my fork, you ll have to reopen all issues on mine ;)

Sorry.

**Comment by kiorky** [comment]
well, just do the PR ones, where tests are needed.

**Comment by josegonzalez** [comment]
Are releases done to your fork or this issue?

**Comment by kiorky** [comment]
i do releases from this fork but most work is done from mine, for historical reasons, taichino one was abandonned for a time.
Now i just try to get them sync'ed.
