### ISSUE TITLE
Wrong behavior around DST change in "America/Sao_Paulo" timezone

### ISSUE THREAD

**Issue by m0nzderr** [taichino/croniter#87]
Consider the following example:
```
import pytz
from datetime import datetime
from croniter import croniter

tz = pytz.timezone("America/Sao_Paulo")

local_dates = [tz.localize(datetime(2018, 2, 17, 0, 0, 0)),
               tz.localize(datetime(2018, 2, 17, 1, 0, 0)),
               tz.localize(datetime(2018, 2, 17, 2, 0, 0)),
               tz.localize(datetime(2018, 2, 17, 3, 0, 0))]

[print(d, '=>', croniter("0 0 * * *", d).get_next(datetime)) for d in local_dates]
```
Output:
> 2018-02-17 00:00:00-02:00 => 2018-02-18 00:00:00-03:00
> 2018-02-17 01:00:00-02:00 => 2018-02-18 00:00:00-03:00
> 2018-02-17 02:00:00-02:00 => 2018-02-18 00:00:00-03:00
> 2018-02-17 03:00:00-02:00 => 2018-02-18 00:00:00-03:00

-This is correct (note the DST changes).

Now lets add 5 minutes to each local date...
```
local_dates = [tz.localize(datetime(2018, 2, 17, 0, 5, 0)),
               tz.localize(datetime(2018, 2, 17, 1, 5, 0)),
               tz.localize(datetime(2018, 2, 17, 2, 5, 0)),
               tz.localize(datetime(2018, 2, 17, 3, 5, 0))]
[print(d, '=>', croniter("0 0 * * *", d).get_next(datetime)) for d in local_dates]
```
Output:
> 2018-02-17 00:05:00-02:00 => 2018-02-17 **23:00:00**-03:00
> 2018-02-17 01:05:00-02:00 => 2018-02-17 **23:00:00**-03:00
> 2018-02-17 02:05:00-02:00 => 2018-02-17 **23:00:00**-03:00
> 2018-02-17 03:05:00-02:00 => 2018-02-17 **23:00:00**-03:00

-This is clearly a BUG!

Just add 1 second, or even 1 microseconds and it brakes. 
Note, that DST in Brazil changes on Feb 18th  2018 at midnight 00:00:00.

The problem disappears for another timezones, e.g., its all good for 2017-03-26 00:05  in 'Europe/Warsaw'. I suggest adding test cases like this one for other timezones as well.

**Comment by kiorky** [comment]
Fixed & release see attached commit.

**Comment by m0nzderr** [comment]
Thanks!
