### ISSUE TITLE
Infinite loop with valid cron syntax

### ISSUE THREAD

**Issue by StasEvseev** [taichino/croniter#98]
Hi guys!

Found issue with specific cron syntax. Could anybody help me with that?

croniter==0.3.16
run on Python2.7

croniter('0 0 29-31 * 3-4', day_or=False).get_prev(datetime.datetime)

It will go in infinite loop.

**Comment by kiorky** [comment]
Closing as not reproducible anymore, feel free to reopen with more details.

```python
>>> import croniter
>>> import datetime
>>> croniter.croniter('0 0 29-31 * 3-4', day_or=False).get_prev(datetime.datetime)
datetime.datetime(2018, 11, 29, 0, 0)
```
